services:

  extract:
    build: ./extract
    container_name: extract
    # ports:
    #   - 8080:8080

  chunk:
    build: ./chunk
    container_name: chunk
    environment:
      # MODEL: mixedbread-ai/mxbai-embed-large-v1
      # MAX_SIZE: 512
      # PAD_LEFT: false
      MODEL: Qwen/Qwen3-Embedding-0.6B
      MAX_SIZE: 8192
      PAD_LEFT: true
    # ports:
    #   - 8090:8080
      
  embed:
    image: ghcr.io/huggingface/text-embeddings-inference:turing-1.8
    container_name: embed
    volumes: # Volumne for data return after restart
      - embed_data:/data
    # ports:
    #   - 8095:80
    # command: "--model-id mixedbread-ai/mxbai-embed-large-v1"
    command: "--model-id Qwen/Qwen3-Embedding-0.6B  --max-client-batch-size 32"
    deploy: 
      resources: 
        reservations: 
          devices: 
          - driver: nvidia 
            count: all 
            capabilities: [gpu]

  store:
    image: pgvector/pgvector:pg17  # Prebuilt Postgres image with pgvector
    container_name: store
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: store_db
    volumes: # Volumne for data return after restart
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d store_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  manage:
    build: ./manage
    container_name: mange
    environment:
      VECTOR_DIM: 1024
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: store_db
      POSTGRES_SERVICEORIP: store
      POSTGRES_PORT: 5432
    depends_on:
      store:
        condition: service_healthy
        restart: true
    ports:
      - 8085:8080
  
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      EXTRACT_SERVICEORIP: extract
      EXTRACT_PORT: 8080
      CHUNK_SERVICEORIP: chunk
      CHUNK_PORT: 8080
      EMBED_SERVICEORIP: embed
      EMBED_PORT: 80
      MANAGE_SERVICEORIP: mange
      MANAGE_PORT: 8080
      EMBED_BATCH_SIZE: 32
    ports:
      - 8081:8080

volumes:
  postgres_data:
  embed_data: