FROM python:3.10.18-alpine3.22

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD [ "fastapi", "run", "server.py", "--port", "8080" ]